### ISSUE TITLE
Remove deprecated text theme getters

### ISSUE THREAD

**Issue by philitell** [philip-brink/DragAndDropLists#97]
Error when running on flutter 3.22:
> drag_and_drop_lists-0.3.3/lib/programmatic_expansion_tile.dart:236:33: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.

**Comment by dmitry-comet** [comment]
https://github.com/philip-brink/DragAndDropLists/pull/98

**Comment by decisionslab2** [comment]
same issue in Flutter 3.22

**Comment by florinleu** [comment]
I think no one is maintaining this anymore. And unfortunately this issue is blocking us from upgrading the flutter version.

**Comment by paulHempel** [comment]
Workaround with #98 fork (thanks @dmitry-comet):

```
  drag_and_drop_lists:
    git:
      url: https://github.com/dmitry-comet/DragAndDropLists.git
      ref: 04715d15ec1a679cf0bc4fcfada75155c9443388
```

Replace the current version in your pubspec.yaml with the git commit.
